version: "3.8"
services:
  cashmanager_api:
    container_name: cashmanager_api
    build: ./backend
    restart: always
    ports:
      - 8080:8080
    environment:
      
     
    volumes:
      - app-volume:/usr/app/data
  cashmanager_apk:
    container_name: cashmanager_apk
    build: ./frontend
    restart: always
    tty: true
    volumes:
      - app-volume:/usr/src/data
volumes:
  app-volume:
  pg-data:
